import { Sides } from "../enums/sides";
import { Shop } from "../shop";

export const Shops: Shop[] = [
  {
    id: 21,
    side: Sides.Top,
    name: "shop",
    color: "red",
    x: 128,
    y: 0,
    height: 128,
    width: 72,
    initialRent: 0,
    rentWithOneHouse: 0,
    rentWithTwoHouses: 0,
    rentWithThreeHouses: 0,
    rentWithFourHouses: 0,
    rentWithHotel: 0,
    purchaseCost: 0,
    houseCost: 0,
    hotelCost: 0,
    mortgageValue: 0,
  },
  {
    id: 9,
    side: Sides.Bottom,
    name: "shop",
    color: "lightblue",
    x: 128,
    y: 776,
    height: 128,
    width: 72,
    initialRent: 0,
    rentWithOneHouse: 0,
    rentWithTwoHouses: 0,
    rentWithThreeHouses: 0,
    rentWithFourHouses: 0,
    rentWithHotel: 0,
    purchaseCost: 0,
    houseCost: 0,
    hotelCost: 0,
    mortgageValue: 0,
  },
  {
    id: 19,
    side: Sides.Left,
    name: "shop",
    color: "orange",
    x: 0,
    y: 128,
    height: 72,
    width: 128,
    initialRent: 0,
    rentWithOneHouse: 0,
    rentWithTwoHouses: 0,
    rentWithThreeHouses: 0,
    rentWithFourHouses: 0,
    rentWithHotel: 0,
    purchaseCost: 0,
    houseCost: 0,
    hotelCost: 0,
    mortgageValue: 0,
  },
  {
    id: 31,
    side: Sides.Right,
    name: "shop",
    color: "green",
    x: 776,
    y: 128,
    height: 72,
    width: 128,
    initialRent: 0,
    rentWithOneHouse: 0,
    rentWithTwoHouses: 0,
    rentWithThreeHouses: 0,
    rentWithFourHouses: 0,
    rentWithHotel: 0,
    purchaseCost: 0,
    houseCost: 0,
    hotelCost: 0,
    mortgageValue: 0,
  },
  {
    id: 22,
    side: Sides.Top,
    name: "shop",
    color: "red",
    x: 200,
    y: 0,
    height: 128,
    width: 72,
    initialRent: 0,
    rentWithOneHouse: 0,
    rentWithTwoHouses: 0,
    rentWithThreeHouses: 0,
    rentWithFourHouses: 0,
    rentWithHotel: 0,
    purchaseCost: 0,
    houseCost: 0,
    hotelCost: 0,
    mortgageValue: 0,
  },
  {
    id: 8,
    side: Sides.Bottom,
    name: "shop",
    color: "lightblue",
    x: 200,
    y: 776,
    height: 128,
    width: 72,
    initialRent: 0,
    rentWithOneHouse: 0,
    rentWithTwoHouses: 0,
    rentWithThreeHouses: 0,
    rentWithFourHouses: 0,
    rentWithHotel: 0,
    purchaseCost: 0,
    houseCost: 0,
    hotelCost: 0,
    mortgageValue: 0,
  },
  {
    id: 18,
    side: Sides.Left,
    name: "shop",
    color: "orange",
    x: 0,
    y: 200,
    height: 72,
    width: 128,
    initialRent: 0,
    rentWithOneHouse: 0,
    rentWithTwoHouses: 0,
    rentWithThreeHouses: 0,
    rentWithFourHouses: 0,
    rentWithHotel: 0,
    purchaseCost: 0,
    houseCost: 0,
    hotelCost: 0,
    mortgageValue: 0,
  },
  {
    id: 32,
    side: Sides.Right,
    name: "shop",
    color: "green",
    x: 776,
    y: 200,
    height: 72,
    width: 128,
    initialRent: 0,
    rentWithOneHouse: 0,
    rentWithTwoHouses: 0,
    rentWithThreeHouses: 0,
    rentWithFourHouses: 0,
    rentWithHotel: 0,
    purchaseCost: 0,
    houseCost: 0,
    hotelCost: 0,
    mortgageValue: 0,
  },
  {
    id: 23,
    side: Sides.Top,
    name: "shop",
    color: "red",
    x: 272,
    y: 0,
    height: 128,
    width: 72,
    initialRent: 0,
    rentWithOneHouse: 0,
    rentWithTwoHouses: 0,
    rentWithThreeHouses: 0,
    rentWithFourHouses: 0,
    rentWithHotel: 0,
    purchaseCost: 0,
    houseCost: 0,
    hotelCost: 0,
    mortgageValue: 0,
  },
  {
    id: 7,
    side: Sides.Bottom,
    name: "shop",
    color: "lightblue",
    x: 272,
    y: 776,
    height: 128,
    width: 72,
    initialRent: 0,
    rentWithOneHouse: 0,
    rentWithTwoHouses: 0,
    rentWithThreeHouses: 0,
    rentWithFourHouses: 0,
    rentWithHotel: 0,
    purchaseCost: 0,
    houseCost: 0,
    hotelCost: 0,
    mortgageValue: 0,
  },
  {
    id: 17,
    side: Sides.Left,
    name: "shop",
    color: "orange",
    x: 0,
    y: 272,
    height: 72,
    width: 128,
    initialRent: 0,
    rentWithOneHouse: 0,
    rentWithTwoHouses: 0,
    rentWithThreeHouses: 0,
    rentWithFourHouses: 0,
    rentWithHotel: 0,
    purchaseCost: 0,
    houseCost: 0,
    hotelCost: 0,
    mortgageValue: 0,
  },
  {
    id: 33,
    side: Sides.Right,
    name: "shop",
    color: "green",
    x: 776,
    y: 272,
    height: 72,
    width: 128,
    initialRent: 0,
    rentWithOneHouse: 0,
    rentWithTwoHouses: 0,
    rentWithThreeHouses: 0,
    rentWithFourHouses: 0,
    rentWithHotel: 0,
    purchaseCost: 0,
    houseCost: 0,
    hotelCost: 0,
    mortgageValue: 0,
  },
  {
    id: 24,
    side: Sides.Top,
    name: "shop",
    color: "red",
    x: 344,
    y: 0,
    height: 128,
    width: 72,
    initialRent: 0,
    rentWithOneHouse: 0,
    rentWithTwoHouses: 0,
    rentWithThreeHouses: 0,
    rentWithFourHouses: 0,
    rentWithHotel: 0,
    purchaseCost: 0,
    houseCost: 0,
    hotelCost: 0,
    mortgageValue: 0,
  },
  {
    id: 6,
    side: Sides.Bottom,
    name: "shop",
    color: "lightblue",
    x: 344,
    y: 776,
    height: 128,
    width: 72,
    initialRent: 0,
    rentWithOneHouse: 0,
    rentWithTwoHouses: 0,
    rentWithThreeHouses: 0,
    rentWithFourHouses: 0,
    rentWithHotel: 0,
    purchaseCost: 0,
    houseCost: 0,
    hotelCost: 0,
    mortgageValue: 0,
  },
  {
    id: 16,
    side: Sides.Left,
    name: "shop",
    color: "orange",
    x: 0,
    y: 344,
    height: 72,
    width: 128,
    initialRent: 0,
    rentWithOneHouse: 0,
    rentWithTwoHouses: 0,
    rentWithThreeHouses: 0,
    rentWithFourHouses: 0,
    rentWithHotel: 0,
    purchaseCost: 0,
    houseCost: 0,
    hotelCost: 0,
    mortgageValue: 0,
  },
  {
    id: 34,
    side: Sides.Right,
    name: "shop",
    color: "green",
    x: 776,
    y: 344,
    height: 72,
    width: 128,
    initialRent: 0,
    rentWithOneHouse: 0,
    rentWithTwoHouses: 0,
    rentWithThreeHouses: 0,
    rentWithFourHouses: 0,
    rentWithHotel: 0,
    purchaseCost: 0,
    houseCost: 0,
    hotelCost: 0,
    mortgageValue: 0,
  },
  {
    id: 25,
    side: Sides.Top,
    name: "shop",
    color: "white",
    x: 416,
    y: 0,
    height: 128,
    width: 72,
    initialRent: 0,
    rentWithOneHouse: 0,
    rentWithTwoHouses: 0,
    rentWithThreeHouses: 0,
    rentWithFourHouses: 0,
    rentWithHotel: 0,
    purchaseCost: 0,
    houseCost: 0,
    hotelCost: 0,
    mortgageValue: 0,
  },
  {
    id: 5,
    side: Sides.Bottom,
    name: "shop",
    color: "white",
    x: 416,
    y: 776,
    height: 128,
    width: 72,
    initialRent: 0,
    rentWithOneHouse: 0,
    rentWithTwoHouses: 0,
    rentWithThreeHouses: 0,
    rentWithFourHouses: 0,
    rentWithHotel: 0,
    purchaseCost: 0,
    houseCost: 0,
    hotelCost: 0,
    mortgageValue: 0,
  },
  {
    id: 15,
    side: Sides.Left,
    name: "shop",
    color: "white",
    x: 0,
    y: 416,
    height: 72,
    width: 128,
    initialRent: 0,
    rentWithOneHouse: 0,
    rentWithTwoHouses: 0,
    rentWithThreeHouses: 0,
    rentWithFourHouses: 0,
    rentWithHotel: 0,
    purchaseCost: 0,
    houseCost: 0,
    hotelCost: 0,
    mortgageValue: 0,
  },
  {
    id: 35,
    side: Sides.Right,
    name: "shop",
    color: "white",
    x: 776,
    y: 416,
    height: 72,
    width: 128,
    initialRent: 0,
    rentWithOneHouse: 0,
    rentWithTwoHouses: 0,
    rentWithThreeHouses: 0,
    rentWithFourHouses: 0,
    rentWithHotel: 0,
    purchaseCost: 0,
    houseCost: 0,
    hotelCost: 0,
    mortgageValue: 0,
  },
  {
    id: 26,
    side: Sides.Top,
    name: "shop",
    color: "yellow",
    x: 488,
    y: 0,
    height: 128,
    width: 72,
    initialRent: 0,
    rentWithOneHouse: 0,
    rentWithTwoHouses: 0,
    rentWithThreeHouses: 0,
    rentWithFourHouses: 0,
    rentWithHotel: 0,
    purchaseCost: 0,
    houseCost: 0,
    hotelCost: 0,
    mortgageValue: 0,
  },
  {
    id: 4,
    side: Sides.Bottom,
    name: "shop",
    color: "brown",
    x: 488,
    y: 776,
    height: 128,
    width: 72,
    initialRent: 0,
    rentWithOneHouse: 0,
    rentWithTwoHouses: 0,
    rentWithThreeHouses: 0,
    rentWithFourHouses: 0,
    rentWithHotel: 0,
    purchaseCost: 0,
    houseCost: 0,
    hotelCost: 0,
    mortgageValue: 0,
  },
  {
    id: 14,
    side: Sides.Left,
    name: "shop",
    color: "pink",
    x: 0,
    y: 488,
    height: 72,
    width: 128,
    initialRent: 0,
    rentWithOneHouse: 0,
    rentWithTwoHouses: 0,
    rentWithThreeHouses: 0,
    rentWithFourHouses: 0,
    rentWithHotel: 0,
    purchaseCost: 0,
    houseCost: 0,
    hotelCost: 0,
    mortgageValue: 0,
  },
  {
    id: 36,
    side: Sides.Right,
    name: "shop",
    color: "blue",
    x: 776,
    y: 488,
    height: 72,
    width: 128,
    initialRent: 0,
    rentWithOneHouse: 0,
    rentWithTwoHouses: 0,
    rentWithThreeHouses: 0,
    rentWithFourHouses: 0,
    rentWithHotel: 0,
    purchaseCost: 0,
    houseCost: 0,
    hotelCost: 0,
    mortgageValue: 0,
  },
  {
    id: 27,
    side: Sides.Top,
    name: "shop",
    color: "yellow",
    x: 560,
    y: 0,
    height: 128,
    width: 72,
    initialRent: 0,
    rentWithOneHouse: 0,
    rentWithTwoHouses: 0,
    rentWithThreeHouses: 0,
    rentWithFourHouses: 0,
    rentWithHotel: 0,
    purchaseCost: 0,
    houseCost: 0,
    hotelCost: 0,
    mortgageValue: 0,
  },
  {
    id: 3,
    side: Sides.Bottom,
    name: "shop",
    color: "brown",
    x: 560,
    y: 776,
    height: 128,
    width: 72,
    initialRent: 0,
    rentWithOneHouse: 0,
    rentWithTwoHouses: 0,
    rentWithThreeHouses: 0,
    rentWithFourHouses: 0,
    rentWithHotel: 0,
    purchaseCost: 0,
    houseCost: 0,
    hotelCost: 0,
    mortgageValue: 0,
  },
  {
    id: 13,
    side: Sides.Left,
    name: "shop",
    color: "pink",
    x: 0,
    y: 560,
    height: 72,
    width: 128,
    initialRent: 0,
    rentWithOneHouse: 0,
    rentWithTwoHouses: 0,
    rentWithThreeHouses: 0,
    rentWithFourHouses: 0,
    rentWithHotel: 0,
    purchaseCost: 0,
    houseCost: 0,
    hotelCost: 0,
    mortgageValue: 0,
  },
  {
    id: 37,
    side: Sides.Right,
    name: "shop",
    color: "blue",
    x: 776,
    y: 560,
    height: 72,
    width: 128,
    initialRent: 0,
    rentWithOneHouse: 0,
    rentWithTwoHouses: 0,
    rentWithThreeHouses: 0,
    rentWithFourHouses: 0,
    rentWithHotel: 0,
    purchaseCost: 0,
    houseCost: 0,
    hotelCost: 0,
    mortgageValue: 0,
  },
  {
    id: 28,
    side: Sides.Top,
    name: "shop",
    color: "yellow",
    x: 632,
    y: 0,
    height: 128,
    width: 72,
    initialRent: 0,
    rentWithOneHouse: 0,
    rentWithTwoHouses: 0,
    rentWithThreeHouses: 0,
    rentWithFourHouses: 0,
    rentWithHotel: 0,
    purchaseCost: 0,
    houseCost: 0,
    hotelCost: 0,
    mortgageValue: 0,
  },
  {
    id: 2,
    side: Sides.Bottom,
    name: "shop",
    color: "brown",
    x: 632,
    y: 776,
    height: 128,
    width: 72,
    initialRent: 0,
    rentWithOneHouse: 0,
    rentWithTwoHouses: 0,
    rentWithThreeHouses: 0,
    rentWithFourHouses: 0,
    rentWithHotel: 0,
    purchaseCost: 0,
    houseCost: 0,
    hotelCost: 0,
    mortgageValue: 0,
  },
  {
    id: 12,
    side: Sides.Left,
    name: "shop",
    color: "pink",
    x: 0,
    y: 632,
    height: 72,
    width: 128,
    initialRent: 0,
    rentWithOneHouse: 0,
    rentWithTwoHouses: 0,
    rentWithThreeHouses: 0,
    rentWithFourHouses: 0,
    rentWithHotel: 0,
    purchaseCost: 0,
    houseCost: 0,
    hotelCost: 0,
    mortgageValue: 0,
  },
  {
    id: 38,
    side: Sides.Right,
    name: "shop",
    color: "blue",
    x: 776,
    y: 632,
    height: 72,
    width: 128,
    initialRent: 0,
    rentWithOneHouse: 0,
    rentWithTwoHouses: 0,
    rentWithThreeHouses: 0,
    rentWithFourHouses: 0,
    rentWithHotel: 0,
    purchaseCost: 0,
    houseCost: 0,
    hotelCost: 0,
    mortgageValue: 0,
  },
  {
    id: 29,
    side: Sides.Top,
    name: "shop",
    color: "yellow",
    x: 704,
    y: 0,
    height: 128,
    width: 72,
    initialRent: 0,
    rentWithOneHouse: 0,
    rentWithTwoHouses: 0,
    rentWithThreeHouses: 0,
    rentWithFourHouses: 0,
    rentWithHotel: 0,
    purchaseCost: 0,
    houseCost: 0,
    hotelCost: 0,
    mortgageValue: 0,
  },
  {
    id: 1,
    side: Sides.Bottom,
    name: "shop",
    color: "brown",
    x: 704,
    y: 776,
    height: 128,
    width: 72,
    initialRent: 0,
    rentWithOneHouse: 0,
    rentWithTwoHouses: 0,
    rentWithThreeHouses: 0,
    rentWithFourHouses: 0,
    rentWithHotel: 0,
    purchaseCost: 0,
    houseCost: 0,
    hotelCost: 0,
    mortgageValue: 0,
  },
  {
    id: 11,
    side: Sides.Left,
    name: "shop",
    color: "pink",
    x: 0,
    y: 704,
    height: 72,
    width: 128,
    initialRent: 0,
    rentWithOneHouse: 0,
    rentWithTwoHouses: 0,
    rentWithThreeHouses: 0,
    rentWithFourHouses: 0,
    rentWithHotel: 0,
    purchaseCost: 0,
    houseCost: 0,
    hotelCost: 0,
    mortgageValue: 0,
  },
  {
    id: 39,
    side: Sides.Right,
    name: "shop",
    color: "blue",
    x: 776,
    y: 704,
    height: 72,
    width: 128,
    initialRent: 0,
    rentWithOneHouse: 0,
    rentWithTwoHouses: 0,
    rentWithThreeHouses: 0,
    rentWithFourHouses: 0,
    rentWithHotel: 0,
    purchaseCost: 0,
    houseCost: 0,
    hotelCost: 0,
    mortgageValue: 0,
  },
];
