import { Sides } from "../enums/sides";
import { Space } from "../models/space";

export const ShopWidthTopBottom = 72;
export const ShopHeightTopBottom = 128;
export const ShopWidthLeftRight = 128;
export const ShopHeightLeftRight = 72;
export const cornerHeightWidth = 128;

export const Spaces: Space[] = [
    {
      index: 0,
      side: null,
      name: "Go",
      color: null,
      x: 776,
      y: 776,
      height: 128,
      width: 128,
      playerY: 0,
    },
    {
      index: 1,
      side: Sides.Bottom,
      name: "shop",
      color: "brown",
      x: 704,
      y: 776,
      height: 128,
      width: 72,
      playerX: -75
    },
    {
      index: 2,
      side: Sides.Bottom,
      name: "shop",
      color: "brown",
      x: 632,
      y: 776,
      height: 128,
      width: 72,
      playerX: -145
    },
    {
      index: 3,
      side: Sides.Bottom,
      name: "shop",
      color: "brown",
      x: 560,
      y: 776,
      height: 128,
      width: 72,
      playerX: -220
    },
    {
      index: 4,
      side: Sides.Bottom,
      name: "shop",
      color: "brown",
      x: 488,
      y: 776,
      height: 128,
      width: 72,
      playerX: -290
    },
    {
      index: 5,
      side: Sides.Bottom,
      name: "shop",
      color: "white",
      x: 416,
      y: 776,
      height: 128,
      width: 72,
      playerX: -360
    },
    {
      index: 6,
      side: Sides.Bottom,
      name: "shop",
      color: "lightblue",
      x: 344,
      y: 776,
      height: 128,
      width: 72,
      playerX: -435
    },
    {
      index: 7,
      side: Sides.Bottom,
      name: "shop",
      color: "lightblue",
      x: 272,
      y: 776,
      height: 128,
      width: 72,
      playerX: -505
    },
    {
      index: 8,
      side: Sides.Bottom,
      name: "shop",
      color: "lightblue",
      x: 200,
      y: 776,
      height: 128,
      width: 72,
      playerX: -580
    },
    {
      index: 9,
      side: Sides.Bottom,
      name: "shop",
      color: "lightblue",
      x: 128,
      y: 776,
      height: 128,
      width: 72,
      playerX: -650
    },
    {
      index: 10,
      side: null,
      name: "Jail/Visiting",
      color: null,
      x: 0,
      y: 776,
      height: 128,
      width: 128,
      playerX: -792
    },
    {
      index: 11,
      side: Sides.Left,
      name: "shop",
      color: "pink",
      x: 0,
      y: 704,
      height: 72,
      width: 128,
      playerY: -75,
    },
    {
      index: 12,
      side: Sides.Left,
      name: "shop",
      color: "pink",
      x: 0,
      y: 632,
      height: 72,
      width: 128,
      playerY: -145,
    },
    {
      index: 13,
      side: Sides.Left,
      name: "shop",
      color: "pink",
      x: 0,
      y: 560,
      height: 72,
      width: 128,
      playerY: -220,
    },
    {
      index: 14,
      side: Sides.Left,
      name: "shop",
      color: "pink",
      x: 0,
      y: 488,
      height: 72,
      width: 128,
      playerY: -290,
    },
    {
      index: 15,
      side: Sides.Left,
      name: "shop",
      color: "white",
      x: 0,
      y: 416,
      height: 72,
      width: 128,
      playerY: -360,
    },
    {
      index: 16,
      side: Sides.Left,
      name: "shop",
      color: "orange",
      x: 0,
      y: 344,
      height: 72,
      width: 128,
      playerY: -435,
    },
    {
      index: 17,
      side: Sides.Left,
      name: "shop",
      color: "orange",
      x: 0,
      y: 272,
      height: 72,
      width: 128,
      playerY: -505,
    },
    {
      index: 18,
      side: Sides.Left,
      name: "shop",
      color: "orange",
      x: 0,
      y: 200,
      height: 72,
      width: 128,
      playerY: -580,
    },
    {
      index: 19,
      side: Sides.Left,
      name: "shop",
      color: "orange",
      x: 0,
      y: 128,
      height: 72,
      width: 128,
      playerY: -650,
    },
    {
      index: 20,
      side: null,
      name: "Free Parking",
      color: null,
      x: 0,
      y: 0,
      height: 128,
      width: 128,
      playerY: -792
    },
    {
      index: 21,
      side: Sides.Top,
      name: "shop",
      color: "red",
      x: 128,
      y: 0,
      height: 128,
      width: 72,
      playerX: -650,
    },
    {
      index: 22,
      side: Sides.Top,
      name: "shop",
      color: "red",
      x: 200,
      y: 0,
      height: 128,
      width: 72,
      playerX: -580,
    },
    {
      index: 23,
      side: Sides.Top,
      name: "shop",
      color: "red",
      x: 272,
      y: 0,
      height: 128,
      width: 72,
      playerX: -505,
    },
    {
      index: 24,
      side: Sides.Top,
      name: "shop",
      color: "red",
      x: 344,
      y: 0,
      height: 128,
      width: 72,
      playerX: -435,
    },
    {
      index: 25,
      side: Sides.Top,
      name: "shop",
      color: "white",
      x: 416,
      y: 0,
      height: 128,
      width: 72,
      playerX: -360,
    },
    {
      index: 26,
      side: Sides.Top,
      name: "shop",
      color: "yellow",
      x: 488,
      y: 0,
      height: 128,
      width: 72,
      playerX: -290,
    },
    {
      index: 27,
      side: Sides.Top,
      name: "shop",
      color: "yellow",
      x: 560,
      y: 0,
      height: 128,
      width: 72,
      playerX: -220,
    },
    {
      index: 28,
      side: Sides.Top,
      name: "shop",
      color: "yellow",
      x: 632,
      y: 0,
      height: 128,
      width: 72,
      playerX: -145,
    },
    {
      index: 29,
      side: Sides.Top,
      name: "shop",
      color: "yellow",
      x: 704,
      y: 0,
      height: 128,
      width: 72,
      playerX: -75,
    },
    {
      index: 30,
      side: null,
      name: "Go to Jail",
      color: null,
      x: 776,
      y: 0,
      height: 128,
      width: 128,
      playerX: 0,
    },
    {
      index: 31,
      side: Sides.Right,
      name: "shop",
      color: "green",
      x: 776,
      y: 128,
      height: 72,
      width: 128,
      playerY: -650,
    },
    {
      index: 32,
      side: Sides.Right,
      name: "shop",
      color: "green",
      x: 776,
      y: 200,
      height: 72,
      width: 128,
      playerY: -580,
    },
    {
      index: 33,
      side: Sides.Right,
      name: "shop",
      color: "green",
      x: 776,
      y: 272,
      height: 72,
      width: 128,
      playerY: -505,
    },
    {
      index: 34,
      side: Sides.Right,
      name: "shop",
      color: "green",
      x: 776,
      y: 344,
      height: 72,
      width: 128,
      playerY: -435,
    },
    {
      index: 35,
      side: Sides.Right,
      name: "shop",
      color: "white",
      x: 776,
      y: 416,
      height: 72,
      width: 128,
      playerY: -360,
    },
    {
      index: 36,
      side: Sides.Right,
      name: "shop",
      color: "blue",
      x: 776,
      y: 488,
      height: 72,
      width: 128,
      playerY: -290,
    },
    {
      index: 37,
      side: Sides.Right,
      name: "shop",
      color: "blue",
      x: 776,
      y: 560,
      height: 72,
      width: 128,
      playerY: -220,
    },
    {
      index: 38,
      side: Sides.Right,
      name: "shop",
      color: "blue",
      x: 776,
      y: 632,
      height: 72,
      width: 128,
      playerY: -145,
    },
    {
      index: 39,
      side: Sides.Right,
      name: "shop",
      color: "blue",
      x: 776,
      y: 704,
      height: 72,
      width: 128,
      playerY: -75,
    },
];